module.exports = {
  type: "object",
  properties: {
    _id: {
      type: "String",
      description: "Autogenerated Id of student",
      readOnly: true,
    },
    firstName: {
      type: "String",
      description: "The first name of the student",
      example: "Solomon",
    },
    lastName: {
      type: "String",
      description: "The last name of the student",
      example: "Grundy",
    },
    email: {
      type: "string",
      description: "Email address of the user",
      example: "solomongrundy@user.com",
    },
    dateOfBirth: {
      type: "string",
      format: "date",
      description: "The date of birth of the student",
    },
    classId: {
      type: "String",
      description: "Autogenerated class ID of the student",
      readOnly: true,
    },
    degreeId: {
      type: "String",
      description: "Autogenerated degree ID of the student",
    },
    address: {
      type: "object",
      description: "Optional user address",
      properties: {
        street: { type: "string", example: "123 Applebay Street" },
        city: { type: "string", example: "Gotham" },
        state: { type: "string", example: "New York" },
        zip: { type: "string", example: "10001" },
        country: { type: "string", example: "USA" },
      },
    },
    createdAt: {
      type: "string",
      format: "date-time",
      readOnly: true,
      description: "Timestamp when the student account was created",
    },
    updatedAt: {
      type: "string",
      format: "date-time",
      readOnly: true,
      description: "Timestamp when the student account was last updated",
    },
  },
  required: [
    "firstName",
    "lastName",
    "email",
    "dateOfBirth",
    "classId",
    "degreeId",
    "address",
  ],
};
